# Generated by Django 5.1.6 on 2025-07-15 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('date', models.DateField()),
                ('available_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bus_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default='AC', max_length=10)),
                ('bus_class', models.CharField(choices=[('Sleeper', 'Sleeper'), ('Seater', 'Seater')], default='Seater', max_length=10)),
                ('pickup_point', models.CharField(default='Main Bus Stop', max_length=100)),
                ('drop_point', models.CharField(default='Main Bus Stop', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('pickup', models.CharField(default='Unknown', max_length=100)),
                ('drop', models.CharField(default='Unknown', max_length=100)),
                ('seat_number', models.CharField(max_length=10)),
                ('bus_type', models.CharField(choices=[('Seater', 'Seater'), ('Sleeper', 'Sleeper')], default='Seater', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('is_booked', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookingapp.bus')),
            ],
        ),
    ]
